{
  imports = [
    ./agenix.nix
    ./audio.nix
    ./boot.nix
    ./catppuccin.nix
    ./chromium.nix
    ./flatpak.nix
    ./fonts.nix
    ./locale.nix
    ./networking.nix
    ./nix-settings.nix
    ./openssh.nix
    ./packages.nix
    ./plasma.nix
    ./plymouth.nix
    ./profile.nix
    ./shell.nix
    ./users.nix
  ];
}
